export const products = [
  {
    id: "1",
    name: "HyperFlow Performance Tee",
    category: "Shirts",
    price: 49,
    originalPrice: 65,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: ["New", "-25%"],
  },
  {
    id: "2",
    name: "AeroFlex Running Shorts",
    category: "Shorts",
    price: 55,
    originalPrice: 70,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: ["New"],
  },
  {
    id: "3",
    name: "Vortex Training Jacket",
    category: "Jackets",
    price: 120,
    originalPrice: 150,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: ["-20%"],
  },
  {
    id: "4",
    name: "Momentum Compression Tights",
    category: "Pants",
    price: 85,
    originalPrice: 100,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: [],
  },
  {
    id: "5",
    name: "Momentum Compression Tights",
    category: "Pants",
    price: 85,
    originalPrice: 100,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: [],
  },
  {
    id: "6",
    name: "Momentum Compression Tights",
    category: "Pants",
    price: 85,
    originalPrice: 100,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: [],
  },
  {
    id: "7",
    name: "Momentum Compression Tights",
    category: "Pants",
    price: 85,
    originalPrice: 100,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: [],
  },
  {
    id: "8",
    name: "Momentum Compression Tights",
    category: "Pants",
    price: 85,
    originalPrice: 100,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/product1.png",
    tags: [],
  },
];
