export const products = [
  {
    id: "1",
    name: "HyperFlow Performance Tee",
    category: "Shirts",
    price: 49,
    originalPrice: 65,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/tee-shirt.webp",
    tags: ["New", "-25%"],
  },
  {
    id: "2",
    name: "AeroFlex Running Hoodie",
    category: "Hoodies",
    price: 55,
    originalPrice: 70,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/hoddie-2.webp",
    tags: ["New"],
  },
  {
    id: "3",
    name: "Vortex Training Hoodie",
    category: "Hoodies",
    price: 120,
    originalPrice: 150,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/hoodie.webp",
    tags: ["-20%"],
  },
  {
    id: "4",
    name: "HyperWear Mug",
    category: "Mugs",
    price: 15,
    originalPrice: 20,
    colors: ["#FFFFFF", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/mug.webp",
    tags: [],
  },
  {
    id: "5",
    name: "HyperWear Mug v2",
    category: "Mugs",
    price: 15,
    originalPrice: 20,
    colors: ["#FFFFFF", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/mug-2.webp",
    tags: [],
  },
  {
    id: "6",
    name: "HyperWear Plushie",
    category: "Plushies",
    price: 25,
    originalPrice: 30,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/plush.jpeg",
    tags: [],
  },
  {
    id: "7",
    name: "HyperWear Cap",
    category: "Caps",
    price: 20,
    originalPrice: 25,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/caps-2.jpg",
    tags: [],
  },
  {
    id: "8",
    name: "Momentum Compression Tights",
    category: "Pants",
    price: 85,
    originalPrice: 100,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/plush-2.jpeg",
    tags: [],
  },
  {
    id: "9",
    name: "HyperFlow Performance Tee",
    category: "Shirts",
    price: 49,
    originalPrice: 65,
    colors: ["#2E2E2E", "#C8F3F3", "#3B8B8B"],
    image: "/products-img/tee-shirt.webp",
    tags: ["New", "-25%"],
  },
];
